apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mcommerce
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: houdaibr/frontend:3.3.3
          ports:
            - containerPort: 3000
       
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mcommerce
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
  type: ClusterIP