apiVersion: apps/v1
kind: Deployment
metadata:
  name: commande
  namespace: mcommerce
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: commande
  template:
    metadata:
      labels:
        app: commande
    spec:
      containers:
        - name: commande-microservice
          image: houdaibr/commande:2.1.1
          ports:
            - containerPort: 5001
          resources: {}
          env:
            - name: MONGO_DB
              valueFrom:
                secretKeyRef:
                  name: mcommerce-secret
                  key: mcommerce-database
            - name: MONGO_SERVICE
              value: mcommerce-mongodb-service
      imagePullSecrets:
        - name: gitlab-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: commande-service
  namespace: mcommerce
spec:
  selector:
    app: commande
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
