apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment-v2
  namespace: mcommerce
  labels:
    app: frontend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
      version: v2
  template:
    metadata:
      labels:
        app: frontend

        version: v2
    spec:
      containers:
      - name: frontend
        image: houdaibr/frontend:3.3.3
        ports:
        - containerPort: 5173
     

